"""
try - block that lets you test a block of code for errors.
except -block lets you handle the error.
finally - block lets you execute code, regardless of
the result of the try and except blocks
"""
try:
    print(x)
except:
    print("an exception occured")
